- name: remove the content of app directory if already exists
ansible.builtin.file:
  path: "{{app_location}}"
  state: absent

- name: create html directory
ansible.builtin.file:
  path: "{{app_location}}"
  state: directory

- name: "unarchive the {{component}} code"
ansible.builtin.unarchive:
  src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
  dest: "{{app_location}}"
  remote_src: yes








